env:
  browser: true
  es6: true
extends:
  - standard
parser: babel-eslint
parserOptions:
  sourceType: module
  ecmaVersion: 2019
  impliedStrict: true
plugins:
  - html
  - standard
rules:
  indent: [2, tab]
  no-tabs: 0
